version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image for toolchain
          command: docker build -t pgrandin/rpi0-buildroot:toolchain toolchain
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: |
            docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push pgrandin/rpi0-buildroot:toolchain

