version: 2

defaults: &defaults
  docker:
    - image: docker:17.05.0-ce-git

jobs:
  build_toolchain:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image for toolchain
          command: sh .circleci/build.sh "toolchain"
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh "toolchain"
      - store_artifacts:
          path: /output

  build_graphics_gtk:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with GTK graphics driver
          command: |
            cp toolchain/rpi0-glibc_defconfig graphics-gtk/
            cat graphics-gtk/navit-gtk_defconfig >> graphics-gtk/rpi0-glibc_defconfig
            mv graphics-gtk/rpi0-glibc_defconfig graphics-gtk/navit-gtk_defconfig
            sh .circleci/build.sh "graphics-gtk"
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh "graphics-gtk"
      - store_artifacts:
          path: /output

  build_graphics_qt5:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with QT5 graphics driver
          command: |
            cp toolchain/rpi0-glibc_defconfig graphics-qt5/
            cat graphics-qt5/navit-qt5_defconfig >> graphics-qt5/rpi0-glibc_defconfig
            mv graphics-qt5/rpi0-glibc_defconfig graphics-qt5/navit-qt5_defconfig
            sh .circleci/build.sh "graphics-qt5"
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh "graphics-qt5"
      - store_artifacts:
          path: /output

workflows:
  version: 2
  build_everything:
    jobs:
      - build_toolchain
      - build_graphics_gtk:
          requires:
            - build_toolchain
      - build_graphics_qt5:
          requires:
            - build_toolchain
