version: 2

jobs:
  build_cherokee:
    docker:
      - image: ubuntu:16.04
        environment:
          target: rpi2
    steps:
      - checkout
      - run:
          name: setup prerequisites
          command: apt-get update && apt-get install -y  expect-dev wget git build-essential file cpio unzip python bc
      - run:
          name: Build image
          command: |
               cd cherokee && bash build.sh
          no_output_timeout: 1200
      - store_artifacts:
          path: cherokee/local_build/buildroot-2017.08/output/images/

workflows:
  version: 2
  build_everything:
    jobs:
      - build_cherokee
