version: 2

defaults: &defaults
  docker:
    - image: ubuntu:16.04
  steps:
    - checkout
    - run:
        name: setup prerequisites
        command: apt-get update && apt-get install -y  expect-dev wget git build-essential file cpio unzip python bc
    - run:
        name: Prepare build
        command: |
             cd cherokee && bash build.sh
        no_output_timeout: 1200
    - run:
        name: Prepare config
        command: |
             cd cherokee/${target}/buildroot-2017.08/ && cat configs/${target}_defconfig ../../glibc_defconfig ../../cherokee_defconfig > configs/cherokee-${target}_defconfig && make defconfig cherokee-${target}_defconfig
        no_output_timeout: 1200
    - restore_cache:
       keys:
         - cache-{{ .Environment.CIRCLE_JOB }}-toolchain-{{ checksum "cherokee/glibc_defconfig" }}
    - run:
        name: Build toolchain
        command: |
             cd cherokee/${target}/buildroot-2017.08/ && make toolchain
        no_output_timeout: 1200
    - run:
        name: Build host-cmake
        command: |
             cd cherokee/${target}/buildroot-2017.08/ && make BR2_JLEVEL=2 host-cmake-rebuild
        no_output_timeout: 1200
    - save_cache:
        key: cache-{{ .Environment.CIRCLE_JOB }}-toolchain-{{ checksum "cherokee/glibc_defconfig" }}
        paths:
          - "cherokee/${CIRCLE_JOB}/buildroot-2017.08/output/host/"
          - "cherokee/${CIRCLE_JOB}/buildroot-2017.08/output/build/host-*"
    - run:
        name: Build kernel
        command: |
             cd cherokee/${target}/buildroot-2017.08/ && make linux-rebuild
        no_output_timeout: 1200
    - restore_cache:
       keys:
         - cache-{{ .Environment.CIRCLE_JOB }}-qt5base-{{ checksum "cherokee/cherokee_defconfig" }}
    - run:
        name: Build qt5base
        command: |
             cd cherokee/${target}/buildroot-2017.08/ && make BR2_JLEVEL=2 qt5base-rebuild
        no_output_timeout: 1200
    - save_cache:
        key: cache-{{ .Environment.CIRCLE_JOB }}-qt5base-{{ checksum "cherokee/cherokee_defconfig" }}
        paths:
          - "cherokee/${CIRCLE_JOB}/buildroot-2017.08/output/build/qt5base-*"
    - run:
        name: Build image
        command: |
             cd cherokee/${target}/buildroot-2017.08/ && make
        no_output_timeout: 1200
    - store_artifacts:
        path: cherokee/${target}/buildroot-2017.08/output/images/

jobs:
  raspberrypi2:
    <<: *defaults
    environment:
      target: raspberrypi3
  raspberrypi3:
    <<: *defaults
    environment:
      target: raspberrypi3

workflows:
  version: 2
  build_everything:
    jobs:
      - raspberrypi2
      - raspberrypi3
