version: 2

jobs:
  build_rpi0_toolchain:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  toolchain
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image for toolchain
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi0_baseimage:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  baseimage
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build base image
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi0_xorg:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  xorg
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with a basic Xorg server
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi0_graphics_gtk:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  graphics-gtk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with GTK graphics driver
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi0_graphics_qt5:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  graphics-qt5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with QT5 graphics driver
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi3_toolchain:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi3
          stage:  toolchain
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image for toolchain
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi3_baseimage:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi3
          stage:  baseimage
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build base image
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi3_xorg:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi3
          stage:  xorg
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with a basic Xorg server
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi3_graphics_gtk:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi3
          stage:  graphics-gtk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with GTK graphics driver
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_rpi3_graphics_qt5:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi3
          stage:  graphics-qt5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with QT5 graphics driver
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

workflows:
  version: 2
  build_everything:
    jobs:
      - build_rpi0_toolchain
      - build_rpi0_baseimage:
          requires:
            - build_rpi0_toolchain
      - build_rpi0_xorg:
          requires:
            - build_rpi0_baseimage
      - build_rpi0_graphics_gtk:
          requires:
            - build_rpi0_xorg
      - build_rpi0_graphics_qt5:
          requires:
            - build_rpi0_baseimage
      - build_rpi3_toolchain
      - build_rpi3_baseimage:
          requires:
            - build_rpi3_toolchain
      - build_rpi3_xorg:
          requires:
            - build_rpi3_baseimage
      - build_rpi3_graphics_gtk:
          requires:
            - build_rpi3_xorg
      - build_rpi3_graphics_qt5:
          requires:
            - build_rpi3_baseimage
