version: 2

defaults: &defaults
  docker:
    - image: ubuntu:18.04
  steps:
    - checkout
    - run:
        name: setup prerequisites
        command: apt-get update && apt-get install -y  expect-dev wget git build-essential file cpio unzip python bc
    - run:
        name: Prepare build
        command: |
             cd cherokee && bash build.sh
        no_output_timeout: 1200
    - run:
        name: Prepare config
        command: |
             cd cherokee/${target}/buildroot-${BUILDROOT_VERSION}/ && cat configs/${target}_defconfig ../../glibc_defconfig ../../cherokee_defconfig > configs/cherokee-${target}_defconfig && make defconfig cherokee-${target}_defconfig
        no_output_timeout: 1200
    - run:
        name: Build toolchain
        command: |
             cd cherokee/${target}/buildroot-${BUILDROOT_VERSION}/ && make toolchain
        no_output_timeout: 1200
    - run:
        name: Build host-cmake
        command: |
             cd cherokee/${target}/buildroot-${BUILDROOT_VERSION}/ && \
             [ -d output/build/host-cmake ] || make BR2_JLEVEL=2 host-cmake-rebuild
        no_output_timeout: 1200
    - run:
        name: Build kernel
        command: |
             cd cherokee/${target}/buildroot-${BUILDROOT_VERSION}/ && \
             [ -d output/build/linux-9126e25b0934bd7bd843763310ea4b34c6e139d0 ] || make linux-rebuild
        no_output_timeout: 1200
    - run:
        name: Build qt5base
        command: |
             cd cherokee/${target}/buildroot-${BUILDROOT_VERSION}/ && \
             [ -d output/build/qt5base-5.9.1 ] || make BR2_JLEVEL=2 qt5base-rebuild
        no_output_timeout: 1200
    - run:
        name: Build qtdeclarative
        command: |
             cd cherokee/${target}/buildroot-${BUILDROOT_VERSION}/ && \
             [ -d output/build/qt5declarative-5.9.1 ] || make BR2_JLEVEL=2 qt5declarative-rebuild
        no_output_timeout: 1200
    - run:
        name: Build image
        command: |
             cd cherokee/${target}/buildroot-${BUILDROOT_VERSION}/ && make \
    - run:
        name: Prepare artifacts
        command: |
            mkdir cherokee/${target}/artifacts/ &&
                mv cherokee/${target}/buildroot-${BUILDROOT_VERSION}/output/images \
                cherokee/${target}/artifacts/images-${BUILDROOT_VERSION}
        no_output_timeout: 1200
    - store_artifacts:
        path: cherokee/raspberrypi2/artifacts/
    - store_artifacts:
        path: cherokee/raspberrypi3/artifacts/


jobs:
  raspberrypi2:
    <<: *defaults
    environment:
      target: raspberrypi2
      BUILDROOT_VERSION: "2018.02.7"
  raspberrypi3:
    <<: *defaults
    environment:
      target: raspberrypi3
      BUILDROOT_VERSION: "2018.02.7"

  powertune_raspberrypi3:
    environment:
      target: raspberrypi3
      product: powertune
      BUILDROOT_VERSION: "2018.02.7"
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: setup prerequisites
          command: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y  expect-dev wget git build-essential file cpio unzip python bc bison flex rsync
      - run:
          name: Prepare build
          command: |
               cd ${product} && bash build.sh
          no_output_timeout: 1200
      - run:
          name: Prepare config
          command: |
            cd ${product}/${target}/buildroot-${BUILDROOT_VERSION}/ && \
            cat configs/${target}_defconfig \
                ../../glibc_defconfig \
                ../../${product}_defconfig > \
            configs/${product}-${target}_defconfig && make defconfig ${product}-${target}_defconfig
          no_output_timeout: 1200
      - restore_cache:
         keys:
           - cache-{{ .Environment.CIRCLE_JOB }}-toolchain-{{ checksum "powertune/glibc_defconfig" }}
      - run:
          name: Download sources
          command: |
               cd ${product}/${target}/buildroot-${BUILDROOT_VERSION}/ && make source
          no_output_timeout: 1200
      - run:
          name: Build toolchain
          command: |
               cd ${product}/${target}/buildroot-${BUILDROOT_VERSION}/ && make BR2_JLEVEL=2 toolchain
          no_output_timeout: 1200
      - run:
          name: Build host-cmake
          command: |
               cd ${product}/${target}/buildroot-${BUILDROOT_VERSION}/ && \
               [ -d output/build/host-cmake ] || make BR2_JLEVEL=2 host-cmake-rebuild
          no_output_timeout: 1200
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-toolchain-{{ checksum "${product}/glibc_defconfig" }}
          paths:
            - "powertune/raspberrypi3/buildroot-2018.02.7/output/host/"
            - "powertune/raspberrypi3/buildroot-2018.02.7/output/build/"
      - restore_cache:
         keys:
           - cache-{{ .Environment.CIRCLE_JOB }}-kernel-9126e25b0934bd7bd843763310ea4b34c6e139d0
      - run:
          name: Build kernel
          command: |
               cd ${product}/${target}/buildroot-${BUILDROOT_VERSION}/ && \
               [ -d output/build/linux-9126e25b0934bd7bd843763310ea4b34c6e139d0 ] || make linux-rebuild
          no_output_timeout: 1200
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-kernel-9126e25b0934bd7bd843763310ea4b34c6e139d0
          paths:
            - "powertune/raspberrypi3/buildroot-2018.02.7/output/linux-9126e25b0934bd7bd843763310ea4b34c6e139d0/"
      - run:
          name: Build image
          command: |
               cd ${product}/${target}/buildroot-${BUILDROOT_VERSION}/ && make
      - run:
          name: Prepare artifacts
          command: |
               mkdir ${product}/output/ && \
               mv ${product}/${target}/buildroot-${BUILDROOT_VERSION}/output/images/sdcard.img ${product}/output/${product}-${target}-${CIRCLE_SHA1}.img
          no_output_timeout: 1200
      - store_artifacts:
          path: powertune/output

workflows:
  version: 2
  build_everything:
    jobs:
      - powertune_raspberrypi3
