version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Setup docker
          command: apt-get update && apt-get install -y docker.io
      - run:
          name: Build image
          command: docker build -t buildroot:gtk .

