version: 2

jobs:
  build_toolchain:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  toolchain
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image for toolchain
          command: sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_graphics_gtk:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  graphics-gtk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with GTK graphics driver
          command: |
            cp toolchain/rpi0-glibc_defconfig graphics-gtk/
            cat graphics-gtk/navit-gtk_defconfig >> graphics-gtk/rpi0-glibc_defconfig
            mv graphics-gtk/rpi0-glibc_defconfig graphics-gtk/navit-gtk_defconfig
            sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

  build_graphics_qt5:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          target: rpi0
          stage:  graphics-qt5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image with QT5 graphics driver
          command: |
            cp toolchain/rpi0-glibc_defconfig graphics-qt5/
            cat graphics-qt5/navit-qt5_defconfig >> graphics-qt5/rpi0-glibc_defconfig
            mv graphics-qt5/rpi0-glibc_defconfig graphics-qt5/navit-qt5_defconfig
            sh .circleci/build.sh
          no_output_timeout: 1200
      - run:
          name: Push to docker
          command: sh .circleci/push.sh
      - store_artifacts:
          path: /output

workflows:
  version: 2
  build_everything:
    jobs:
      - build_toolchain
      - build_graphics_gtk:
          requires:
            - build_toolchain
      - build_graphics_qt5:
          requires:
            - build_toolchain
