#!/bin/sh
#
# Starts the gps daemon.
#

NAME=gpsd
DAEMON=/usr/sbin/$NAME
DEVICES="-n /dev/ttyS1 -n /dev/ttyACM0 -n /dev/ttyUSB0"
PIDFILE=/var/run/$NAME.pid

start() {
        printf "Starting $NAME: "
	date -s "2017-12-21"
        start-stop-daemon -S -q -p $PIDFILE --exec $DAEMON -- -P $PIDFILE $DEVICES && echo "OK" || echo "Failed"
}
stop() {
        printf "Stopping $NAME: "
        start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
        rm -f $PIDFILE
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
